### ISSUE TITLE
AWS braket python sdk: user is not authorized to perform on quantum device

### ISSUE THREAD

**Issue by astrung** [aws/amazon-braket-sdk-python#395] opened 2022-06-28 10:51 UTC
I have installed boto3, aws cli, and python-braket-sdk. I have run `aws configure`, and config with my IAM user. My IAM user isn't root user, but it has `AdministratorAccess`, `AmazonBraketFullAccess`, `AmazonBraketJobsExecutionPolicy` policies. 

But if I tried to get some quantum device by this command:`aws braket get-device --device-arn arn:aws:braket:::device/qpu/ionq/ionQdevice`, it always return this error: 

`An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::178363055402:user/hblab-rnd is not authorized to perform: braket:GetDevice on resource: arn:aws:braket::178363055402:device/qpu/ionq/ionQdevice with an explicit deny`

If I run same below python from this link: https://github.com/aws/amazon-braket-sdk-python#usage, it also return similar error:

    import boto3
    from braket.aws import AwsDevice
    from braket.circuits import Circuit
    device = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1")
    bell = Circuit().h(0).cnot(0, 1)
    task = device.run(bell, shots=100)
    print(task.result().measurement_counts)

Error output:

    AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice 
    operation: User: arn:aws:iam::178363055402:user/hblab-rnd is not authorized to perform: 
    braket:GetDevice on resource: arn:aws:braket::178363055402:device/quantum-simulator/amazon/sv1 
    with an explicit deny

I have already added permissions for Braket, but I can not figure the reason for this bug. Please help  

**System information**
- **aws cli**: aws-cli/2.7.11 Python/3.9.11 Windows/10 exe/AMD64 prompt/off
- **Amazon Braket Python SDK version**: 1.25.2
- **Amazon Braket schemas**: 1.10.0
- **Amazon Braket default simulator**: 1.6.2
- **Python version**: 3.8.13

**Comment by speller26** [comment] 2022-06-28 23:46
Have you enabled third-party devices? If you haven't yet, visit the Amazon Braket console, go to **Permissions and settings**, read the notice, and if you agree, click **Accept terms and enable**. Without doing this, you won't be able to access third-party quantum devices, only the Amazon Braket simulators.

<img width="1727" alt="Screen Shot 2022-06-28 at 3 56 06 PM" src="https://user-images.githubusercontent.com/15883075/176322516-c7b12ca4-8b80-41e4-adb3-aa5daaffdb18.png">

**Comment by astrung** [comment] 2022-06-29 02:43
@speller26 
 I have enable this config, I also have create a execution role for "Service-linked role" and "Jobs". But nothing helps. But when I tried to run this command with my root account, everything is fine. I don't know what is problem with IAM account

**Comment by virajvchaudhari** [comment] 2022-07-03 03:38
I wasn't able to reproduce this at my end looks like something incorrect with IAM configuration. Can you try using the command `rm -rf .aws` to remove the current credentials and then performing the `aws configure` command once more with a new access ID and key for the same user with attached policies?

And then try running `aws braket get-device --device-arn arn:aws:braket:::device/qpu/ionq/ionQdevice`. Also make sure to set Default region name as us-east-1 before running this command.

**Comment by virajvchaudhari** [comment] 2022-07-07 19:23
@astrung This looks like a duplicate of question on [quantum computing stack exchange](https://quantumcomputing.stackexchange.com/questions/27115/aws-braket-python-sdk-user-is-not-authorized-to-perform-on-quantum-device). Closing this issue since you have found the answer, feel free to re-open if you need any further assistance.

**Closed by virajvchaudhari** 2022-07-07 19:23 UTC
Labels: bug
