### ISSUE TITLE
`run_batch` for AHS Local Simulator

### ISSUE THREAD

**Issue by weinbe58** [aws/amazon-braket-sdk-python#515] opened 2023-03-14 20:48 UTC
**Describe the feature you'd like**
Much like the `run_batch` for the AHS local simulator device 

**How would this feature be used? Please describe.**
I would like to be able to debug both the generation of batch tasks as well as analysis of batch task results on the local simulator so having the same workflow would be helpful. Otherwise there is little point to using the batch feature for the actual device as most of my development and workflow will only be targeting single tasks. 

**Describe alternatives you've considered**
Currently I am just using single tasks and managing the data myself, effectively not fully utilizing the braket SDK to its fullest potential.

**Comment by math411** [comment] 2023-03-17 16:35
Hello @weinbe58, thank you for raising this issue. Currently, we have https://github.com/aws/amazon-braket-sdk-python/issues/320 open as a good first issue. If this is something you'd like to contribute to, we would be happy to provide guidance for this.

**Comment by weinbe58** [comment] 2023-03-23 14:24
@math411 Ah sorry I did not do an initial search for this issue! 

I would love to help out. Not entirely sure where to begin with the AWS code base.

**Comment by math411** [comment] 2023-03-28 07:28
As a starting point, [the contributing guildelines](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) has a good description of getting started working with the code base including pulling down the code locally, testing, and commit message formats. 

For the particular aspect of batch execution, the [initial commit](https://github.com/aws/amazon-braket-sdk-python/commit/67266974c51cfed49613b503378f748d32174b4c) for `run_batch` would be a good place to see the code changes that were done for `AwsDevice`.

If you have more questions around these links or questions I missed answering, feel free to ask about those!

**Comment by kshitijc** [comment] 2023-05-24 22:18
Resolving since this is a duplicate of #320

**Closed by kshitijc** 2023-05-24 22:18 UTC
